using System.Runtime.InteropServices;
using Garyon.Attributes;

namespace Garyon.QualityControl.SizedStructs
{
    /// <summary>A struct with a size of 30 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct30 : ISizedStruct<Struct30>
    {
        private const int elementCount = 30;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct30 left, Struct30 right) => left.Equals(right);
        public static bool operator !=(Struct30 left, Struct30 right) => !(left == right);
        public static Struct30 operator ~(Struct30 s)
        {
            var result = new Struct30();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct30 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct30)obj);
        }
    }
}
