using System.Runtime.InteropServices;
using Garyon.Attributes;
using System;

namespace Garyon.QualityControl.SizedStructs
{
    /// <summary>A struct with a size of 24 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct24 : ISizedStruct<Struct24>
    {
        private const int elementCount = 24;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct24 left, Struct24 right) => left.Equals(right);
        public static bool operator !=(Struct24 left, Struct24 right) => !(left == right);
        public static Struct24 operator ~(Struct24 s)
        {
            var result = new Struct24();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct24 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct24)obj);
        }
        public override int GetHashCode()
        {
            var result = new HashCode();
            for (int i = 0; i < elementCount; i++)
                result.Add(elements[i]);
            return result.ToHashCode();
        }
    }
}
