using System.Runtime.InteropServices;
using Garyon.Attributes;
using System;

namespace Garyon.QualityControl.SizedStructs
{
    /// <summary>A struct with a size of 25 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct25 : ISizedStruct<Struct25>
    {
        private const int elementCount = 25;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct25 left, Struct25 right) => left.Equals(right);
        public static bool operator !=(Struct25 left, Struct25 right) => !(left == right);
        public static Struct25 operator ~(Struct25 s)
        {
            var result = new Struct25();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct25 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct25)obj);
        }
        public override int GetHashCode()
        {
            var result = new HashCode();
            for (int i = 0; i < elementCount; i++)
                result.Add(elements[i]);
            return result.ToHashCode();
        }
    }
}
