using System.Runtime.InteropServices;
using Garyon.Attributes;

namespace Garyon.QualityControl.SizedStructs
{
    /// <summary>A struct with a size of 18 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct18 : ISizedStruct<Struct18>
    {
        private const int elementCount = 18;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct18 left, Struct18 right) => left.Equals(right);
        public static bool operator !=(Struct18 left, Struct18 right) => !(left == right);
        public static Struct18 operator ~(Struct18 s)
        {
            var result = new Struct18();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct18 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct18)obj);
        }
    }
}
