using System;
using System.Runtime.InteropServices;
using Garyon.Attributes;

namespace Garyon.QualityControl.SizedStructs
{
    /// <summary>A struct with a size of 15 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct15 : ISizedStruct<Struct15>
    {
        private const int elementCount = 15;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct15 left, Struct15 right) => left.Equals(right);
        public static bool operator !=(Struct15 left, Struct15 right) => !(left == right);
        public static Struct15 operator ~(Struct15 s)
        {
            var result = new Struct15();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct15 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct15)obj);
        }
        public override int GetHashCode()
        {
            var result = new HashCode();
            for (int i = 0; i < elementCount; i++)
                result.Add(elements[i]);
            return result.ToHashCode();
        }
    }
}
