using System.Runtime.InteropServices;
using Garyon.Attributes;

namespace Garyon.QualityControl.SizedStructs
{
    /// <summary>A struct with a size of 21 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct21 : ISizedStruct<Struct21>
    {
        private const int elementCount = 21;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct21 left, Struct21 right) => left.Equals(right);
        public static bool operator !=(Struct21 left, Struct21 right) => !(left == right);
        public static Struct21 operator ~(Struct21 s)
        {
            var result = new Struct21();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct21 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct21)obj);
        }
    }
}
