using System.Runtime.InteropServices;
using Garyon.Attributes;

namespace Garyon.QualityControl.SizedStructs
{
    /// <summary>A struct with a size of 23 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct23 : ISizedStruct<Struct23>
    {
        private const int elementCount = 23;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct23 left, Struct23 right) => left.Equals(right);
        public static bool operator !=(Struct23 left, Struct23 right) => !(left == right);
        public static Struct23 operator ~(Struct23 s)
        {
            var result = new Struct23();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct23 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct23)obj);
        }
    }
}
