using System.Runtime.InteropServices;
using Garyon.Attributes;

namespace Garyon.QualityControl.SizedStructs
{
    /// <summary>A struct with a size of 11 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct11 : ISizedStruct<Struct11>
    {
        private const int elementCount = 11;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct11 left, Struct11 right) => left.Equals(right);
        public static bool operator !=(Struct11 left, Struct11 right) => !(left == right);
        public static Struct11 operator ~(Struct11 s)
        {
            var result = new Struct11();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct11 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct11)obj);
        }
    }
}
