using System.Runtime.InteropServices;
using Garyon.Attributes;

namespace Garyon.QualityControl.SizedStructs
{
    /// <summary>A struct with a size of 10 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct10 : ISizedStruct<Struct10>
    {
        private const int elementCount = 10;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct10 left, Struct10 right) => left.Equals(right);
        public static bool operator !=(Struct10 left, Struct10 right) => !(left == right);
        public static Struct10 operator ~(Struct10 s)
        {
            var result = new Struct10();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct10 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct10)obj);
        }
    }
}
