using System;
using System.CodeDom.Compiler;

namespace Garyon.Attributes;

/// <summary>Indicates that the attributed member's code is autogenerated from a code generation tool, without requiring a tool name or version unlike <seealso cref="GeneratedCodeAttribute"/>.</summary>
[AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
public class AutogeneratedAttribute : Attribute
{
}
