using System;

namespace Garyon.Attributes
{
    /// <summary>Indicates that the attributed member's code is autogenerated from a code generation tool.</summary>
    [AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = true)]
    public class AutogeneratedAttribute : Attribute
    {
    }
}
