using Garyon.Attributes;
using System.Runtime.InteropServices;

namespace Garyon.Tests.Resources.SizedStructs
{
    /// <summary>A struct with a size of 27 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct27 : ISizedStruct<Struct27>
    {
        private const int elementCount = 27;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct27 left, Struct27 right) => left.Equals(right);
        public static bool operator !=(Struct27 left, Struct27 right) => !(left == right);
        public static Struct27 operator ~(Struct27 s)
        {
            var result = new Struct27();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct27 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct27)obj);
        }
    }
}
