using Garyon.Attributes;
using System.Runtime.InteropServices;

namespace Garyon.Tests.Resources.SizedStructs
{
    /// <summary>A struct with a size of 31 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct31 : ISizedStruct<Struct31>
    {
        private const int elementCount = 31;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct31 left, Struct31 right) => left.Equals(right);
        public static bool operator !=(Struct31 left, Struct31 right) => !(left == right);
        public static Struct31 operator ~(Struct31 s)
        {
            var result = new Struct31();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct31 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct31)obj);
        }
    }
}
