using Garyon.Attributes;
using System.Runtime.InteropServices;

namespace Garyon.Tests.Resources.SizedStructs
{
    /// <summary>A struct with a size of 12 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct12 : ISizedStruct<Struct12>
    {
        private const int elementCount = 12;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct12 left, Struct12 right) => left.Equals(right);
        public static bool operator !=(Struct12 left, Struct12 right) => !(left == right);
        public static Struct12 operator ~(Struct12 s)
        {
            var result = new Struct12();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct12 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct12)obj);
        }
    }
}
