using Garyon.Attributes;
using System.Runtime.InteropServices;

namespace Garyon.Tests.Resources.SizedStructs
{
    /// <summary>A struct with a size of 7 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct7 : ISizedStruct<Struct7>
    {
        private const int elementCount = 7;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct7 left, Struct7 right) => left.Equals(right);
        public static bool operator !=(Struct7 left, Struct7 right) => !(left == right);
        public static Struct7 operator ~(Struct7 s)
        {
            var result = new Struct7();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct7 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct7)obj);
        }
    }
}
