using Garyon.Attributes;
using System.Runtime.InteropServices;

namespace Garyon.Tests.Resources.SizedStructs
{
    /// <summary>A struct with a size of 14 bytes.</summary>
    [StructLayout(LayoutKind.Sequential, Size = elementCount)]
    [Autogenerated]
    public unsafe struct Struct14 : ISizedStruct<Struct14>
    {
        private const int elementCount = 14;

        private fixed byte elements[elementCount];

        public static bool operator ==(Struct14 left, Struct14 right) => left.Equals(right);
        public static bool operator !=(Struct14 left, Struct14 right) => !(left == right);
        public static Struct14 operator ~(Struct14 s)
        {
            var result = new Struct14();
            for (int i = 0; i < elementCount; i++)
                result.elements[i] = (byte)~s.elements[i];
            return result;
        }

        public bool Equals(Struct14 other)
        {
            for (int i = 0; i < elementCount; i++)
                if (elements[i] != other.elements[i])
                    return false;
            return true;
        }
        public override bool Equals(object obj)
        {
            return Equals((Struct14)obj);
        }
    }
}
