using Garyon.Attributes;
using Garyon.QualityControl.SizedStructs;
using NUnit.Framework;

namespace Garyon.Tests.Resources.SizedStructs
{
    public class SizedStructsSizeTests
    {
        [Autogenerated]
        [Test]
        public unsafe void TestSizes()
        {
            Assert.AreEqual(3, sizeof(Struct3));
            Assert.AreEqual(5, sizeof(Struct5));
            Assert.AreEqual(6, sizeof(Struct6));
            Assert.AreEqual(7, sizeof(Struct7));
            Assert.AreEqual(9, sizeof(Struct9));
            Assert.AreEqual(10, sizeof(Struct10));
            Assert.AreEqual(11, sizeof(Struct11));
            Assert.AreEqual(12, sizeof(Struct12));
            Assert.AreEqual(13, sizeof(Struct13));
            Assert.AreEqual(14, sizeof(Struct14));
            Assert.AreEqual(15, sizeof(Struct15));
            Assert.AreEqual(17, sizeof(Struct17));
            Assert.AreEqual(18, sizeof(Struct18));
            Assert.AreEqual(19, sizeof(Struct19));
            Assert.AreEqual(20, sizeof(Struct20));
            Assert.AreEqual(21, sizeof(Struct21));
            Assert.AreEqual(22, sizeof(Struct22));
            Assert.AreEqual(23, sizeof(Struct23));
            Assert.AreEqual(24, sizeof(Struct24));
            Assert.AreEqual(25, sizeof(Struct25));
            Assert.AreEqual(26, sizeof(Struct26));
            Assert.AreEqual(27, sizeof(Struct27));
            Assert.AreEqual(28, sizeof(Struct28));
            Assert.AreEqual(29, sizeof(Struct29));
            Assert.AreEqual(30, sizeof(Struct30));
            Assert.AreEqual(31, sizeof(Struct31));
        }
    }
}
