using Garyon.Attributes;
using Garyon.QualityControl.SizedStructs;
using System.Threading.Tasks;
using TUnit.Assertions;
using TUnit.Assertions.Extensions;
using TUnit.Core;

namespace Garyon.Tests.Resources.Tests;

public class SizedStructsSizeTests
{
    [Autogenerated]
    [Test]
    public async Task TestSizes()
    {
        await Assert.That(SizeOf<Struct3>()).IsEqualTo(3);
        await Assert.That(SizeOf<Struct5>()).IsEqualTo(5);
        await Assert.That(SizeOf<Struct6>()).IsEqualTo(6);
        await Assert.That(SizeOf<Struct7>()).IsEqualTo(7);
        await Assert.That(SizeOf<Struct9>()).IsEqualTo(9);
        await Assert.That(SizeOf<Struct10>()).IsEqualTo(10);
        await Assert.That(SizeOf<Struct11>()).IsEqualTo(11);
        await Assert.That(SizeOf<Struct12>()).IsEqualTo(12);
        await Assert.That(SizeOf<Struct13>()).IsEqualTo(13);
        await Assert.That(SizeOf<Struct14>()).IsEqualTo(14);
        await Assert.That(SizeOf<Struct15>()).IsEqualTo(15);
        await Assert.That(SizeOf<Struct17>()).IsEqualTo(17);
        await Assert.That(SizeOf<Struct18>()).IsEqualTo(18);
        await Assert.That(SizeOf<Struct19>()).IsEqualTo(19);
        await Assert.That(SizeOf<Struct20>()).IsEqualTo(20);
        await Assert.That(SizeOf<Struct21>()).IsEqualTo(21);
        await Assert.That(SizeOf<Struct22>()).IsEqualTo(22);
        await Assert.That(SizeOf<Struct23>()).IsEqualTo(23);
        await Assert.That(SizeOf<Struct24>()).IsEqualTo(24);
        await Assert.That(SizeOf<Struct25>()).IsEqualTo(25);
        await Assert.That(SizeOf<Struct26>()).IsEqualTo(26);
        await Assert.That(SizeOf<Struct27>()).IsEqualTo(27);
        await Assert.That(SizeOf<Struct28>()).IsEqualTo(28);
        await Assert.That(SizeOf<Struct29>()).IsEqualTo(29);
        await Assert.That(SizeOf<Struct30>()).IsEqualTo(30);
        await Assert.That(SizeOf<Struct31>()).IsEqualTo(31);

        // Bypassing the inability to await inside unsafe code
        static unsafe int SizeOf<T>()
            where T : unmanaged
        {
            return sizeof(T);
        }
    }
}
