using Garyon.FrameworkCapabilityGenerator.FrameworkCapabilities;
using Garyon.FrameworkCapabilityGenerator.MsBuildElements;
using Garyon.FrameworkCapabilityGenerator.NetVersioning;
using System.Text;
using System.Xml.Linq;

namespace Garyon.FrameworkCapabilityGenerator;

// Intentionally avoiding using the Microsoft.Build package due to its
// complicated design that is unnecessary for this case

internal static class FrameworkCapabilityGeneratorHelpers
{
    internal static string GenerateProps()
    {
        var projectElement = GeneratePropsElement();
        return $"""
            <!-- Generated by Garyon.FrameworkCapabilityGenerator -->

            {ConvertToString(projectElement)}
            """;
    }

    private static string ConvertToString(XElement element)
    {
        return element
            .ToString()
            .Replace("&#xD;&#xA;", "\r\n")
            ;
    }

    private static XElement GeneratePropsElement()
    {
        var project = new Project();

        foreach (var capability in KnownFrameworkCapabilities.Capabilities)
        {
            if (capability.Capabilities is [])
            {
                continue;
            }

            var supportedVersions = capability.VersionRange
                .Reduce(GaryonTargetFrameworkVersions.Versions);

            if (supportedVersions is [])
            {
                continue;
            }

            var element = GenerateCapabilityPropertyGroup(capability, supportedVersions);
            project.Elements.Add(element);
        }

        return project.ToXElement();
    }

    private static PropertyGroup GenerateCapabilityPropertyGroup(
        FrameworkCapabilityRange capability,
        IReadOnlyList<BaseFrameworkVersion> supportedVersions)
    {
        // Property group condition
        const string conditionIndentation = "    ";
        const string conditionJoiner = $" Or\r\n{conditionIndentation}";

        var conditionBuilder = new StringBuilder();
        conditionBuilder
            .AppendLine()
            .Append(conditionIndentation);

        AppendValues(
            conditionBuilder,
            supportedVersions,
            AddCondition,
            conditionJoiner);

        var condition = conditionBuilder.ToString();

        // DefineConstants
        const string defineConstantsIndentation = "      ";
        const string defineConstantsJoiner = $"\r\n{defineConstantsIndentation}";

        var defineConstantsContentBuilder = new StringBuilder();

        defineConstantsContentBuilder
            .AppendLine()
            .Append(defineConstantsIndentation)
            .AppendLine("$(DefineConstants)")
            .Append(defineConstantsIndentation)
            ;

        AppendValues(
            defineConstantsContentBuilder,
            capability.Capabilities,
            AddDefinedConstant,
            defineConstantsJoiner);

        defineConstantsContentBuilder
            .AppendLine()
            .Append(conditionIndentation);

        var defineConstantsContent = defineConstantsContentBuilder.ToString();

        return new()
        {
            Condition = condition,
            Properties =
            {
                new PropertyGroup.PropertyElement
                {
                    Name = "DefineConstants",
                    Value = defineConstantsContent,
                }
            }
        };

        static void AddCondition(StringBuilder conditionBuilder, BaseFrameworkVersion version)
        {
            var monikerName = version.MonikerName;
            conditionBuilder
                .Append($"'$(TargetFramework)' == '{monikerName}'");
        }

        static void AddDefinedConstant(StringBuilder conditionBuilder, string capability)
        {
            conditionBuilder
                .Append(capability)
                .Append(';');
        }
    }

    private static StringBuilder Append<T>(
        StringBuilder builder,
        IEnumerable<T> values,
        StringBuilderAppender<T> appender,
        char delimiter)
    {
        var hasFirst = false;
        foreach (var value in values)
        {
            if (hasFirst)
            {
                builder.Append(delimiter);
            }

            hasFirst = true;
            appender(builder, value);
        }

        return builder;
    }

    private static StringBuilder AppendValues<T>(
        StringBuilder builder,
        IEnumerable<T> values,
        StringBuilderAppender<T> appender,
        string delimiter)
    {
        var hasFirst = false;
        foreach (var value in values)
        {
            if (hasFirst)
            {
                builder.Append(delimiter);
            }

            hasFirst = true;
            appender(builder, value);
        }

        return builder;
    }

    private delegate void StringBuilderAppender<T>(StringBuilder builder, T value);
}
